# -*- coding: utf-8 -*-
"""Project 2: Restaurants Market Analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1R3eE6pmrBwfJAo2Ecejm20YT3PBcAR-o

**Course:** CSIT553_03SP24 EXPLORATORY DATA ANALYSIS & VISUALIZATION

**Student:** Shibbir Ahmed Arif

**Project Group:** 08

# **Comprehensive Market Analysis of USA Fast Food Restaurants**
"""

# Load the Drive helper and mount
from google.colab import drive
drive.mount('/content/drive')

"""# **Data Description**

**Fast Food Restaurants Across America**

This is a dataset of 10,000 fast food restaurants provided by Datafiniti's Business Database. The dataset includes the restaurant's address, city, latitude and longitude coordinates, name, and more. Data is collected from 2014 to 2019.

**Dataset Source:** https://data.world/datafiniti/fast-food-restaurants-across-america

# **Objective**

In this project, I chose the fast food industry for analysis, mainly focusing on the distribution of American fast food restaurants in various states/ provinces, and studied the openness of the market, analyzed the opportunity for new stores to get benefits, and provided some possible opening locations for new fast food restaurants to be open. I can consider this dataset to be representative of broader market and draw my conclusions.

# **Steps**


1.   Data Collection
2.   Import Necessary Libraries
3.   Data Load
4.   Data Exploration
5.   Data Cleaning
6.   Data Analysis
7.   Map Visualization
8.   Aggregation Visualization
9.   Interactive Visualization
10.  Conclusion

**Import Necessary Libraries**
"""

pip install folium

import numpy as np
import pandas as pd
pd.options.display.max_rows = 10
import matplotlib.pyplot as plt
import seaborn as sns
import folium
import re
from folium.plugins import FastMarkerCluster
import plotly.express as px
import warnings
warnings.simplefilter(action='ignore', category=FutureWarning)

"""# **Load The Data**"""

df = pd.read_csv("/content/drive/MyDrive/Dataset/Datafiniti_Fast_Food_Restaurants_Jun19.csv")
df.head()

"""# **Data Exploration**"""

df.shape

df.columns

df.info()

"""**Checking Missing Values**"""

df.isnull().sum()

"""As we can see that there are some missing values in the dataset

**Checking Duplicate Values**
"""

df.duplicated().any()

"""As we can see the output is False, meaning there is no duplicate data in the dataset

# **Data Cleaning**

**Remove Unnecessary Columns**
"""

df.drop(columns=['id', 'dateAdded', 'dateUpdated','categories', 'primaryCategories', 'keys', 'sourceURLs', 'websites'], inplace=True)

# shape of dataset
print("Dimension after dropping columns:")
print(df.shape)

df.head()

"""**Summary Statistics**"""

# Display summary statistics for numerical columns
summary_stats_numeric = df.describe()
print("Summary Statistics for Numerical Columns:")
print(summary_stats_numeric)

# Display summary statistics for categorical columns
summary_stats_categorical = df.describe(include='object')
print("\nSummary Statistics for Categorical Columns:")
print(summary_stats_categorical)

"""In **Province** column, OH (Ohio) is the top value which shows occurrance 922 times.

In **City** column, Columbus is the top value which shows occurance 105 times.

In **Name** column, McDonald's is the top value which shows occurence 765 times.

# **Data Analysis**

**How many fast food restauraunts are recorded?**
"""

print("Number of unique restaurant:", df['name'].nunique())

"""**Which cities are crowded with fast food restaurants?**"""

print("Number of unique cities:", df['city'].nunique())
nameplot = df['city'].value_counts()[:20].plot.bar(title='Top 20 Cities')
nameplot.set_xlabel('city',size=20)
nameplot.set_ylabel('count',size=20)

"""Let's run pandas data . describe() function to see the min, max, and mean of number of fast food restaurants in different cities"""

rest_count_by_city = df['city'].value_counts()
rest_count_by_city.describe()

"""**Many cities has only 1-3 restaurants opened and the mean number of restaurants opened is 3.55**

**How many cities have opened less than 4 fast food restaurants?**
"""

print(len(rest_count_by_city[rest_count_by_city < 4]), "cities opened less than 4 fast food restaurants")
print("They are", round(100*len(rest_count_by_city[rest_count_by_city < 4])/len(rest_count_by_city),2), "%"),
print("of the total cities recorded in the dataset")

"""**1. The analysis of market openness and opportunities**"""

# Group dataset by province and count the number of restaurants

df1 = df.groupby('province').size().reset_index(name='restaurant_count')
df1 = df1.sort_values(by='restaurant_count', ascending=False)
df1

# Create the bar chart
plt.figure(figsize=(15, 5))
plt.bar(df1['province'], df1['restaurant_count'])
plt.xticks(rotation=50)
plt.xlabel('Province')
plt.ylabel('Number of Restaurants')
plt.title('Number of Restaurants per Province')
plt.show()

"""# **Interactive Map Visualization 1**

**Finding out provinces with less than 100 and 50 restaurants**
"""

states_less_100 = df1[df1['restaurant_count'] < 100]
states_less_100

states_less_50 = df1[df1['restaurant_count'] < 50]
states_less_50

# Merge the two datasets
merged_df = pd.concat([states_less_50, states_less_100]).drop_duplicates()

# Plot the choropleth map
fig = px.choropleth(merged_df,
                     locations='province',
                     locationmode='USA-states',
                     scope='usa',
                     color='restaurant_count',
                     hover_name='province',
                     color_continuous_scale=px.colors.sequential.Plasma,
                     range_color=(0, 100),
                     title='Provinces with Less Than 50 or 100 Restaurants',
                     labels={'restaurant_count': 'Restaurant Count'}
                    )

# Add slider for filtering less than 50 and less than 100 restaurants
fig.update_layout(
    sliders=[
        {
            'steps': [
                {'method': 'update', 'label': 'Less Than 50', 'args': [{'visible': [True]}, {'title': 'Provinces with Less Than 50 Restaurants'}]},
                {'method': 'update', 'label': 'Less Than 100', 'args': [{'visible': [True]}, {'title': 'Provinces with Less Than 100 Restaurants'}]}
            ]
        }
    ]
)

# Add click event to update map with selected province
fig.update_traces(marker_line_width=0.5, selector=dict(type='choropleth'))
fig.update_layout(clickmode='event+select')

fig.show()

"""**Observation:**
Select the above areas where the amount of stores is less than 50 or 100 for the development of new fast food stores, having a large relatively unopened market and being given more opportunities, reducing competition with strong competitors in bustling areas.

**Now, I will break up over 50 odd states into key regions to learn Brand strenghs at regional level. First lets take a closer look at dataset by plotting them on Map**

**2. Overview of Fast Food Restaurant Landscape**

**Lets obtain presence of restaurants at Regional level**

# **Interactive Map Visualization 2**
"""

lats = df['latitude'].tolist()
lons = df['longitude'].tolist()
locations = list(zip(lats, lons))

map1 = folium.Map(location=[37.0902, -95.7129], zoom_start=5)
FastMarkerCluster(data=locations).add_to(map1)
map1

"""**I see presence across all the states with Georgia, Indiana and Florida leading the way. Now lets split the entire market into 4 key regions**"""

#split the entire market into 4 key regions
def market(x):

    if x in ('WA','OR','CA','NV','AZ','NM','CO','WY','MT','ID','AK','HI'):
        return "West"
    elif x in ('ND','MN','IA','SD','KS','NE','MO','WI','MI','IL','IN','OH'):
        return "Mid West"
    elif x in ('NY','NJ','PA','CT','RI','MA','ME','NH','VT'):
        return "North East"
    else:
        return "South"

df['region']=df['province'].apply(market)
df.head()

"""# **Interactive Aggregation Visualization 1**"""

# Grouping by 'region' and 'province', and calculating the percentage of restaurants
d1 = df.groupby(['region', 'province']).agg({'name': 'count'}).reset_index()
d1['Total_Region'] = d1.groupby('region')['name'].transform('sum')
d1['Perc_Region'] = (d1['name'] / d1['Total_Region']) * 100
d1['Perc_Region'] = d1['Perc_Region'].round(1)

# Separate DataFrame for each region
d11 = d1[d1['region'] == 'West'].sort_values('Perc_Region', ascending=True)
d12 = d1[d1['region'] == 'Mid West'].sort_values('Perc_Region', ascending=True)
d13 = d1[d1['region'] == 'North East'].sort_values('Perc_Region', ascending=True)
d14 = d1[d1['region'] == 'South'].sort_values('Perc_Region', ascending=True)

# Bar chart
fig = px.bar(d1, x='province', y='Perc_Region', color='region',
             title="Fast Food Restaurant Presence (%): Percentages are at Regional Level and not Overall")
fig.update_layout(xaxis_title="State", yaxis_title="Percentage")
fig.show()

"""**Observation**
- In the West, California accounts for 32.4% of the total number of restaurants, and Washington and Oregon are still a long way off, accounting for about 18% and 14.9% respectively.

- Florida (15.8%) and North Carolina (14.2%) are the top two markets in the South, while Pennsylvania (52.2%) and New York (46.5%) lead the Northeast.

- In the Midwest, Ohio has the highest at about 34%.

**Now an overall view as well of fast food restaurants**
"""

state_counts = df.groupby(['province']).agg({'name':'count'})
state_counts.columns = ['Count of Brands']
state_counts.sort_values('Count of Brands',ascending=False,inplace=True)
state_counts.reset_index(inplace=True)

state_counts['Perc']=100*state_counts['Count of Brands']/state_counts['Count of Brands'].sum()

fig=px.bar(state_counts,x="province",y="Perc")
fig.update_traces(marker_color='Turquoise')
fig.update_layout(xaxis_title="State",yaxis_title="Percentage",title="Fast Food Restaurant Presence(%)")
fig.show()

"""**Observation**

- Ohio (9.2%), Florida (7.3%), California (7.2%), North Carolina (6.6%) and Alabama (6.3%) are top 5 markets in US
- Connecticut, Massachusetts, New Jersey, North Dakota rank least

**3. Analyze Brand Presence by Geographics**

# **Interactive Aggregation Visualization 2**

**Lets examine market share by Region**
"""

region_counts=df.groupby(['region']).agg({'name':'count'})
region_counts.columns=['Count of Brands']

region_counts.sort_values('Count of Brands', ascending=False,inplace=True)
region_counts['perc']=100*region_counts['Count of Brands']/region_counts['Count of Brands'].sum()
region_counts.reset_index(inplace=True)

fig=px.pie(region_counts,values='perc',names='region',title='Brand Presence by Region',width=600,height=500,
           color_discrete_sequence=px.colors.sequential.RdBu)
fig.show()

"""**Observation**

- With 46.7% of fast food restaurants located at South takes the top spot while North East contains only 3.72%.

- For Brands looking to enter the market or expand their footprint, South and Mid West are favourable.

# **Interactive Aggregation Visualization 3**

**Let's obtain an idea of top brands in the dataset**
"""

df['name']=df.name.str.replace('$','')
df['name']=df.name.str.replace("'",'')
df['name']=df.name.str.lower()
df['name']=df.name.map(lambda x: re.sub(r'\W+','',x))

Brand_1=df.groupby(['name']).agg({'name':'count'})
Brand_1.columns=['number']
Brand_1=Brand_1.sort_values('number',ascending=False)

Brand_1.nlargest(15,'number').index

"""**I am going to focus on top 7 brands only. I will filter out them from main dataset to inform my further analysis**"""

Brands = ['mcdonalds', 'burgerking', 'tacobell', 'wendys', 'arbys', 'kfc','subway']

# Filter the DataFrame for the specified brands
df1 = df[df.name.isin(Brands)]

# Group by region and brand, and count the number of stores
d1 = df1.groupby(['region', 'name']).agg({'name':'count'})
d1.columns = ['Stores']
d1.reset_index(inplace=True)

# Sort the DataFrame by region and number of stores
d1.sort_values(['region', 'Stores'], ascending=[True, False], inplace=True)
d1.reset_index(drop=True, inplace=True)

# Plot
fig = px.scatter(d1, x="Stores", y="name", color="region",
                 title="Brand Presence by Region-Store Counts",
                 labels={"Stores": "Store Count"},
                 width=800, height=600
                )

fig.update_layout(
    margin=dict(l=20, r=20, t=25, b=20)
)
fig.show()

"""**Observation**

Subway, McDonalds, Taco Bell, KFC, Burger King, Wendys and Arbys are the most popular Brands. Clearly all the Brands have big presence in South followed by Mid West.

**Lets obtain Brand Penetration at Region to confirm the above view**
"""

d2 = d1.copy()

d2.set_index(['region', 'name'], inplace=True)

# Calculate the percentage of stores for each region
d2['Percentage'] = d2.groupby(level=0)['Stores'].transform(lambda x: 100 * x / x.sum())

# Reset index to convert the multi-index back to columns
d2.reset_index(inplace=True)

# Plot
fig2 = px.histogram(d2, x="region", y="Percentage", color="name",
                    title="Brand Presence by Region",
                    width=800, height=500)

fig2.show()

"""**Observation**

- Subway market penetration is above 28% in Mid West, South and West regions with highest of 31.6% in Mid West
- Burger King has higher penetration in North East after McDonalds and Subway.
- Taco Bell has concentrated more in West
- Arbys has least presence in West

# **Interactive Aggregation Visualization 4**

**Lets now obtain further granular insights of Brand Penetration by State level**
"""

d3 = df1.groupby(['province','name']).agg({'name':'count'})
d3.columns=['Stores']
d3['Percentage']=d3['Stores'].groupby(level=0).transform(lambda x:100*x/x.sum())
d3.reset_index(inplace=True)

fig4=px.histogram(d3,x="province",y="Percentage",color="name",
                 title="Brand Penetration by State")
fig4.show()

"""**Observation**

- Analyzing by state I learn the top markets for each brand. I observe that they are present in most of the markets.
- In Washington, D.C. only 2 brands are present
- For McDonalds, Washington, D.C., Hawaii and Arizona are key markets.
- Wendys is present in all states except Wincosin, South Dakota, Wyoming and Hawaii
- For Arbys, Wyoming and South Dakota are the key ones.
- KFC is absent in 4 states. They are - Kentucky, Montana, North Dakota and Wyoming

# **Conclusion**

**Market Landscape**

Most of the fast food restaurants are located in South and Mid West. Further in each of the four regions few states have higher market share than others by large margin. Apart from having large urban centers, favourable business environment may also be factor for ex: lower taxes, state grants in establishing new stores, less stringent labor laws etc.

At National level, Ohio, Florida, California, North Carolina and Alabama are top states attracting most of the businesses

**Brand Presence**

Top Brands have presence in almost all geographies with Subway having more stores than others by a considerable margin. This tells us that key growth strategy for Brands has been "Market Development" i.e offer products/services in newer markets as a way to grow revenues.

Subway share is above 28% in all regions followed by McDonald's at 20-28%.
Given the ubiquitous presence of brands, there is intense stiff competition in market. This creates added pressure on Brands to differentiate their product offerings which opens up opportunities for Brands to leverage their strengths while others face headwinds if they don't adapt in time. In market characterized by high volume-low margin transactions mere survival may not be best long term strategy
"""

